### PR TITLE
Added Toggle Buttons  for Feed and Leaderboard And online people list also aligned home

### PR DESCRIPTION
**Pull request by YogPanjarale**
Added Toggle Buttons  for Feed and Leaderboard And online people list also aligned home page
TODO: To add icons for button
@ManavSaspal <:sedcatgun:772699366082215936>

### CODE REVIEW

**Comment by ManavSaspal** [comment]
Icons Missing in the buttons

**Comment by ManavSaspal** [comment]
The people's tab in the feed tab is just spread out to full height and is exceeding some browser's height.

**Comment by ManavSaspal** [comment]
PFPs' green borders looking weird and not really enclosing the pfps fully.

**Comment by ManavSaspal** [comment]
The line under the active tab is missing.

**Comment by ManavSaspal** [comment]
also fix this:
image
try decreasing the time font i guess, we can afford that.

**Comment by YogPanjarale** [comment]
> The people's tab in the feed tab is just spread out to full height and is exceeding some browser's height.
 
@ManavSaspal  fixed in 95190bd
image

**Comment by ManavSaspal** [comment]
nice

**Comment by YogPanjarale** [comment]
> also fix this:
> image
> try decreasing the time font i guess, we can afford that.

fixed in 
035509e

**Comment by YogPanjarale** [comment]
image

**Comment by YogPanjarale** [comment]
> PFPs' green borders looking weird and not really enclosing the pfps fully.

fixed  in 2776f45
image

**Comment by YogPanjarale** [comment]
For now 
1. Icons Missing in the buttons
2. The line under the active tab is missing.

closing the PR here You can make issue about it

**Pull request merged**
